name: Sauvegarde Webcam Lille
on:
  # schedule:
  #   - cron: '*/1 * * * *'  # Exécute toutes les 1 minute
  workflow_dispatch:  # Permet de le lancer manuellement
jobs:
  capture_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Installer les dépendances
        run: pip install requests
      - name: Créer un dossier pour les images
        run: |
          mkdir -p ./images  # Créer un dossier appelé 'images' s'il n'existe pas déjà
      - name: Télécharger l'image
        run: |
          python -c "
          import requests
          from datetime import datetime, timedelta  # Ajout de timedelta ici
          url = 'https://www.meteo-lille.fr/meteo_cam.php?u=1738844192591'  # URL de l'image
          img_data = requests.get(url).content  # Télécharger l'image
          timestamp = (datetime.now() + timedelta(hours=1)).strftime('%Y-%m-%d_%H-%M-%S') # Ajouter 1h à l'horodatage
          file_path = f'./images/webcam_{timestamp}.jpg'  # Spécifier le chemin de sauvegarde
          with open(file_path, 'wb') as handler:
              handler.write(img_data)  # Sauvegarder l'image dans le dossier 'images'
          "
      - name: Commit et push des images
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Utilisation du token secret pour l'authentification
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git  # Authentification avec le token
          git add ./images/*  # Ajouter les nouvelles images dans le dossier 'images'
          git commit -m 'Ajout nouvelle image' || echo "Aucune modification à commit"
          git push
